name = "Snailshell"
license = "MIT"
licenselink = "https://github.com/dfego/hugo-theme-snailshell/LICENSE"
description = "A Bootstrap-based theme for an artist's personal website."

# The home page of the theme, where the source can be found
homepage = "https://github.com/dfego/hugo-theme-snailshell/"

# If you have a running demo of the theme
# demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ["personal", "portfolio", "responsive", "gallery", "bootstrap"]
# features = ['some', 'awesome', 'features']

[author]
name = "Dan Fego"
# homepage = 'Your website'
